<?php
/**
 * Implementation of hook_permission
 */
function uni_emergency_tools_permission() {
  $permissions['access emergency tools'] = array(
    'title' => 'Access UNI emergency tools',
    'description' => 'Provides access to links for use during a major emergency.',
  );
    
  return $permissions;
}

/**
 * Implementation of hook_menu
 */
function uni_emergency_tools_menu() {  
  $items['admin/emergency'] = array(
    'title' => 'Emergency Tools',
    'description' => 'Use the UNI low-bandwidth theme.',
    'page callback' => 'uni_emergency_tools_page',
    'access arguments' => array('access emergency tools'),
    'position' => 'left',
    'weight' => 10,
    'file' => 'uni_emergency_tools.pages.inc',
  );

  return $items;
}