<?php 

/**
 * Implementation of hook_wysiwyg_plugin()
 *
 * Adds the TinyMCE Legacy Output plugin to WYSIWYG
**/

function tinymce_legacy_wysiwyg_plugin($editor, $version) {
  switch($editor) {
    case 'tinymce':
      return array(
        'legacyoutput' => array(
       	  'path' => $editor['library path'] . '/plugins/legacyoutput',
          'extensions' => array('legacyoutput' => t('Legacy Output')),
          'load' => TRUE,
          'internal' => TRUE,
          ),
      );
  }
}